base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  acc_lim_x: 0.55
  acc_lim_theta: 3.14

  max_vel_x: 0.45
  max_vel_x_backwards: 0.2

  max_vel_theta: 0.2

  min_turning_radius: 3

  wheelbase: 0.2
  cmd_angle_instead_rotvel: true


