obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[0.05, 0.05], [-0.05, 0.05], [-0.05, -0.05], [0.05, -0.05]]
inflation_radius: 0.10

observation_sources: laser_scan_sensor 

static_map: false

map_topic: /hector/map

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
