obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[0.2, 0.1], [-0.2, 0.1], [-0.2, -0.1], [0.2, -0.1]]
inflation_radius: 0.5

observation_sources: laser_scan_sensor 

static_map: false

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
